FROM node:22-alpine

WORKDIR /app

# Copy only dependency files
COPY package*.json pnpm-lock.yaml ./

# Enable pnpm
RUN corepack enable pnpm

# Install dependencies using the lockfile
RUN pnpm install --frozen-lockfile

# Copy source code
COPY . .

ENV CHOKIDAR_USEPOLLING=true
ENV HOSTNAME=0.0.0.0
EXPOSE 3000

# Run dev server
CMD ["pnpm", "dev"]
